/*
 * ConnectorFrame.java
 *
 * Created on October 15, 2003, 6:12 PM
 */

package presentation;

import java.util.Hashtable;
import java.util.Vector;

import componentmodel.Connector;

import java.util.Enumeration;
/**
 *
 * @author  alla
 */
public class ConnectorFrame extends javax.swing.JFrame {
    
    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	/***/
    private Hashtable<Object, Object> componentHash = new Hashtable<Object, Object>();
    private Vector<Connector> connectorVector = new Vector<Connector>();
    private Vector<String> compInVector = new Vector<String>();
    private Vector<String> compOutVector = new Vector<String>();
    
    /** Creates new form ConnectorFrame */
    public ConnectorFrame() {
        initComponents();
    }
    
    public void setComponentHash(Hashtable<Object, Object> _componentHash){
        componentHash = _componentHash;
    }
    
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        ButtonPanel = new javax.swing.JPanel();
        confimeJButton = new javax.swing.JButton();
        OutPanel = new javax.swing.JPanel();
        outJLabel = new javax.swing.JLabel();
        outComboBox = new javax.swing.JComboBox<String>();
        InPanel = new javax.swing.JPanel();
        inJLabel = new javax.swing.JLabel();
        inComboBox = new javax.swing.JComboBox<String>();

        setTitle("Set connector");
        setMaximizedBounds(new java.awt.Rectangle(1000, 100, 1000, 1000));
        setName("ConnectorFrame");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        confimeJButton.setText("Ok");
        confimeJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confimeJButtonActionPerformed(evt);
            }
        });

        ButtonPanel.add(confimeJButton);

        getContentPane().add(ButtonPanel, java.awt.BorderLayout.SOUTH);

        OutPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        outJLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        outJLabel.setText("Component Out");
        OutPanel.add(outJLabel);

        OutPanel.add(outComboBox);

        getContentPane().add(OutPanel, java.awt.BorderLayout.CENTER);

        InPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        inJLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        inJLabel.setText("Component In");
        InPanel.add(inJLabel);

        InPanel.add(inComboBox);

        getContentPane().add(InPanel, java.awt.BorderLayout.NORTH);

        setBounds(50, 50, 300, 135);
    }//GEN-END:initComponents
    
    private void confimeJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confimeJButtonActionPerformed
        String componentNameIn;
        String componentNameOut;
        
        if(compInVector.size() == 0){
            this.setVisible(false);
            return;
        }
        
        componentmodel.Component componentModelIn;
        componentmodel.Component componentModelOut;
        componentmodel.Connector connectorModel;
        
        componentNameIn  = inComboBox.getSelectedItem().toString();
        componentNameOut = outComboBox.getSelectedItem().toString();
        if(componentNameIn.equals(componentNameOut)){
            javax.swing.JOptionPane.showMessageDialog(this, "You must enter different components");
            return;
        }
        componentModelIn  = (componentmodel.Component)this.componentHash.get(componentNameIn);
        compInVector.addElement(componentNameIn);
        componentModelOut = (componentmodel.Component)this.componentHash.get(componentNameOut);
        compOutVector.addElement(componentNameOut);
        connectorModel = new componentmodel.Connector(componentModelIn, componentModelOut);
        connectorVector.addElement(connectorModel);
        
        javax.swing.JOptionPane.showMessageDialog(this, "Connector correctly created");
        this.setVisible(false);
    }//GEN-LAST:event_confimeJButtonActionPerformed
    
    /** Exit the Application */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        //this.exitForm(evt.WINDOW_CLOSING);
    }//GEN-LAST:event_exitForm
    
    public void setComboBox(){
        @SuppressWarnings("unused")
		int numberItem;
        String compName;
        componentmodel.Component componentModel;
        Enumeration<Object> elementsHash;
        
        elementsHash = this.componentHash.elements();
        inComboBox.removeAllItems();
        outComboBox.removeAllItems();
        while(elementsHash.hasMoreElements()){
            componentModel = (componentmodel.Component)elementsHash.nextElement();
            compName = componentModel.getType();
            if(!compInVector.contains(compName)){
                inComboBox.addItem(compName);
            }
            if(!compOutVector.contains(compName)){
                outComboBox.addItem(compName);
            }
        }
    }
    
    /***/
    public Vector<Connector> getConnectorVector(){
        return connectorVector;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        new ConnectorFrame().setVisible(true);
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ButtonPanel;
    private javax.swing.JPanel InPanel;
    private javax.swing.JPanel OutPanel;
    private javax.swing.JButton confimeJButton;
    private javax.swing.JComboBox<String> inComboBox;
    private javax.swing.JLabel inJLabel;
    private javax.swing.JComboBox<String> outComboBox;
    private javax.swing.JLabel outJLabel;
    // End of variables declaration//GEN-END:variables
    
}
