/*
 * Wizard.java
 *
 * Created on November 10, 2003, 3:10 PM
 */

package presentation.wizard;

/**
 *
 * @author  alla
 */
public class Wizard extends javax.swing.JFrame {
    
    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	/** Creates new form Wizard */
    public Wizard() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        @SuppressWarnings("unused")
		java.awt.GridBagConstraints gridBagConstraints;

        MainPanel = new javax.swing.JPanel();
        TopPanel = new javax.swing.JPanel();
        nameLabel = new javax.swing.JLabel();
        nameTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        MainPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 0, 0));

        TopPanel.setLayout(new java.awt.GridLayout(2, 2, 1, 1));

        TopPanel.setBorder(new javax.swing.border.EtchedBorder(java.awt.Color.white, java.awt.Color.white));
        TopPanel.setMinimumSize(new java.awt.Dimension(400, 50));
        TopPanel.setPreferredSize(new java.awt.Dimension(400, 50));
        nameLabel.setText("Component Name:");
        TopPanel.add(nameLabel);

        nameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTextFieldActionPerformed(evt);
            }
        });

        TopPanel.add(nameTextField);

        jLabel3.setText("jLabel3");
        TopPanel.add(jLabel3);

        TopPanel.add(jTextField3);

        MainPanel.add(TopPanel);

        getContentPane().add(MainPanel, java.awt.BorderLayout.CENTER);

        pack();
    }//GEN-END:initComponents

    private void nameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTextFieldActionPerformed
        // Add your handling code here:
    }//GEN-LAST:event_nameTextFieldActionPerformed
    
    /** Exit the Application */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        new Wizard().setVisible(true);
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel MainPanel;
    private javax.swing.JPanel TopPanel;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField nameTextField;
    // End of variables declaration//GEN-END:variables
    
}
